/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 scene.gltf --transform
Author: Wayne Pearce (https://sketchfab.com/WaynePearce10)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/simple-galaxy-simulation-58e7b5996f674caeaa3ec2c9df371212
Title: Simple Galaxy Simulation
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Galaxy(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "./models/galaxy/scene-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions.Action.timeScale = 0.1;
    actions.Action.play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Root">
            <group
              name="Sphere002"
              rotation={[Math.PI / 2, 0.01, 0]}
              scale={2.14}
            >
              <mesh
                name="Sphere002_0"
                geometry={nodes.Sphere002_0.geometry}
                material={materials.Root}
              />
            </group>
            <group name="Sphere" scale={5}>
              <mesh
                name="Sphere_0"
                geometry={nodes.Sphere_0.geometry}
                material={materials.Root}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/galaxy/scene-transformed.glb");
